export * from './Header/Header'
export * from './Genre badge/GenreBadge'
export * from './Movie info/MovieInfo'
export * from './Movies list/MoviesList'
export * from './User info/UserInfo'
export * from './Movies list card/MoviesListCard'
export * from './Stars rating/StarsRating'
export * from './Genre/Genre'
export * from './Genre list/GenreList'
export * from './Footer/Footer'
